const reviews=[
    { id:1,
     name: "Ant",
     category: "Animal",
     image:'https://www.westernpest.com/wp-content/uploads/1odorous-house-ant-300x200.jpg',
     text:
        'Ants are eusocial insects of the family Formicidae and, along with the related wasps and bees, belong to the order Hymenoptera. Ants appear in the fossil record across the globe in considerable diversity during the latest Early Cretaceous and early Late Cretaceous, suggesting an earlier origin. ',
    },
    { id:2,
     name: "Banana",
     category: "Fruit",
     image:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSxYFUQ9SNxzUnaa2i5oxRPPbw_9KY-RydL1Q&usqp=CAU',
     text:'A banana is an elongated, edible fruit – botanically a berry produced by several kinds of large herbaceous flowering plants in the genus Musa. In some countries, bananas used for cooking may be called "plantains", distinguishing them from dessert bananas. ',
    },
    { id:3,
     name: "Carrot",
     category: "Vegetable",
     image:'https://www.pngitem.com/pimgs/m/135-1359965_transparent-carrots-png-vegetable-carrot-png-download.png',
     text:'The carrot (Daucus carota subsp. sativus) is a root vegetable, typically orange in color, though purple, black, red, white, and yellow cultivars exist, all of which are domesticated forms of the wild carrot, Daucus carota, native to Europe and Southwestern Asia. ',
    },
    { id:4,
     name: "Diamond",
     category: "Jewelery",
     image:'https://assets.entrepreneur.com/content/3x2/2000/20160305000536-diamond.jpeg',
     text:'Diamond is a solid form of the element carbon with its atoms arranged in a crystal structure called diamond cubic. At room temperature and pressure, another solid form of carbon known as graphite is the chemically stable form of carbon, but diamond converts to it extremely slowly. ',
    },
    { id:5,
     name: "Eagle",
     category: "Bird",
     image:'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Eagle_on_roots_-_crop_3_%28430008061%29.jpg/640px-Eagle_on_roots_-_crop_3_%28430008061%29.jpg',
     text:'Eagle is the common name for many large birds of prey of the family Accipitridae. Eagles belong to several groups of genera, some of which are closely related. Most of the 60 species of eagle are from Eurasia and Africa. Outside this area, just 14 species can be found—2 in North America.',  
     },
    { id:6,
     name: "Four",
     category: "Number",
     image:'https://cdn4.vectorstock.com/i/1000x1000/91/98/kids-playing-with-big-number-four-vector-23609198.jpg',
     text:'Four is the smallest composite number, its proper divisors being 1 and 2. 4 is the smallest squared prime (p2) and the only even number in this form. 4 is also the only square one more than a prime number.A number is a multiple of 4 if its last two digits are a multiple of 4.',
    }
 ];
 export default reviews;